PREFIX dbpedia-ja: <http://ja.dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

//search country old
//bug no russia
SELECT ?country ?label
WHERE
{
    ?country wdt:P31 wd:Q6256.
    ?country rdfs:label ?label filter (lang(?label) = "zh").
}

//search country new
SELECT ?country ?countryLabel WHERE {
  ?country wdt:P463 wd:Q1065.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "zh". }
}

//Japan airport
SELECT ?airport ?airportLabel ?place_served ?coor ?website ?image WHERE {
  ?airport wdt:P17 wd:Q17;
    wdt:P31 wd:Q1248784;
    wdt:P931 ?place_served;
    wdt:P625 ?coor;
    wdt:P856 ?website;
    wdt:P18 ?image.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}

# Get latitude longitude coordinates of capital
# Gelatitude longitude coordinates of birth place
SELECT DISTINCT ?countryLabel ?capitalLabel ?population ?capital_lon ?capital_lat ?mayorLabel ?birth_date ?age ?birth_place ?birth_placeLabel ?birth_place_lon ?birth_place_lat WHERE {
  ?country wdt:P17 wd:Q17;
    wdt:P36 ?capital.
  OPTIONAL { ?capital wdt:P1082 ?population. }
  ?capital (p:P625/psv:P625) ?capital_node.
  ?capital_node wikibase:geoLatitude ?capital_lat;
    wikibase:geoLongitude ?capital_lon.
  ?capital p:P6 ?statement.
  ?statement ps:P6 ?mayor.
  FILTER(NOT EXISTS { ?statement pq:P582 ?end_date. })
  ?mayor wdt:P569 ?birth_date.
  BIND((YEAR(NOW())) - (YEAR(?birth_date)) AS ?age)
  ?mayor wdt:P19 ?birth_place.
  ?birth_place wdt:P625 ?birth_place_coordinates;
    (p:P625/psv:P625) ?birth_place_node.
  ?birth_place_node wikibase:geoLatitude ?birth_place_lat;
    wikibase:geoLongitude ?birth_place_lon.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}