PREFIX dbpedia-ja: <http://ja.dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

//search country old
//bug no russia
SELECT ?country ?label
WHERE
{
    ?country wdt:P31 wd:Q6256.
    ?country rdfs:label ?label filter (lang(?label) = "zh").
}

//search country new
SELECT ?country ?countryLabel WHERE {
  ?country wdt:P463 wd:Q1065.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "zh". }
}

//Japan airport
SELECT ?airport ?airportLabel ?place_served ?coor ?website ?image WHERE {
  ?airport wdt:P17 wd:Q17;
    wdt:P31 wd:Q1248784;
    wdt:P931 ?place_served;
    wdt:P625 ?coor;
    wdt:P856 ?website;
    wdt:P18 ?image.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}

# Destinations from Antwerp International airport

SELECT ?connectsairport ?connectsairportLabel ?place_served ?place_servedLabel ?coor ?image
WHERE
{
  VALUES ?airport { wd:Q17480 } # Antwerp international airport  wd:Q17480
  ?airport wdt:P81 ?connectsairport ;
           wdt:P625 ?base_airport_coor .
  ?connectsairport wdt:P931 ?place_served ;
                   wdt:P625 ?coor ;
                   wdt:P18 ?image .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}